"""
Fix Missing parent_act Fields in Manifest

Manually adds parent_act to regulations that are missing it.
"""

import yaml
from pathlib import Path


def fix_parent_acts(manifest_path: str = "data/raw/manifest.yaml"):
    """Fix known missing parent_act references."""

    # Known parent acts for specific regulations
    KNOWN_PARENT_ACTS = {
        "SOR-2021-181": "Bank Act (S.C.1991, c. 46)",  # Financial Consumer Protection Framework
        # Add more manual mappings here as needed
    }

    print(f"📝 Fixing parent_act references in: {manifest_path}")
    print()

    path = Path(manifest_path)

    with open(path, 'r', encoding='utf-8') as f:
        manifest = yaml.safe_load(f)

    documents = manifest.get('documents', [])
    fixed_count = 0

    for doc in documents:
        if doc.get('category') == 'regulation' and 'parent_act' not in doc:
            # Try to find parent act by citation
            citation = doc.get('citation', '')

            # Extract just the citation part (e.g., "SOR-2021-181" from "SOR/2021-181")
            citation_normalized = citation.replace('/', '-')

            if citation_normalized in KNOWN_PARENT_ACTS:
                parent = KNOWN_PARENT_ACTS[citation_normalized]
                doc['parent_act'] = parent
                print(f"✅ Fixed: {doc.get('filename')}")
                print(f"   Added parent_act: {parent}")
                fixed_count += 1
            else:
                print(f"⚠️  Unknown parent act for: {doc.get('filename')}")
                print(f"   Citation: {citation}")
                print(f"   Add to KNOWN_PARENT_ACTS dict in this script")

    if fixed_count > 0:
        # Backup original
        backup_path = path.parent / f"{path.stem}.before_fix.yaml"
        import shutil
        shutil.copy2(path, backup_path)
        print(f"\n💾 Backup created: {backup_path.name}")

        # Write fixed manifest
        with open(path, 'w', encoding='utf-8') as f:
            f.write("# Auto-generated by Legislative Mapper\n")
            f.write(f"# Fixed parent_act references\n\n")

            yaml.dump(
                {"documents": documents},
                f,
                default_flow_style=False,
                allow_unicode=True,
                sort_keys=False,
            )

        print(f"\n✅ Fixed {fixed_count} regulation(s)")
        print(f"   Saved to: {manifest_path}")
    else:
        print("\n✅ No fixes needed")


if __name__ == "__main__":
    fix_parent_acts()
